# Form implementation generated from reading ui file 'd:\NEW PROJECT\Interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(712, 540)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 221, 171))
        self.frame.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lineHost = QtWidgets.QLineEdit(parent=self.frame)
        self.lineHost.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.lineHost.setObjectName("lineHost")
        self.lineUser = QtWidgets.QLineEdit(parent=self.frame)
        self.lineUser.setGeometry(QtCore.QRect(10, 50, 131, 31))
        self.lineUser.setObjectName("lineUser")
        self.linePasswd = QtWidgets.QLineEdit(parent=self.frame)
        self.linePasswd.setGeometry(QtCore.QRect(10, 90, 131, 31))
        self.linePasswd.setObjectName("linePasswd")
        self.buttonConnect = QtWidgets.QPushButton(parent=self.frame)
        self.buttonConnect.setGeometry(QtCore.QRect(10, 130, 201, 31))
        self.buttonConnect.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.buttonConnect.setObjectName("buttonConnect")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(150, 20, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, 100, 49, 16))
        self.label_3.setObjectName("label_3")
        self.logotipo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logotipo.setGeometry(QtCore.QRect(250, 20, 451, 171))
        self.logotipo.setText("")
        self.logotipo.setPixmap(QtGui.QPixmap("d:\\NEW PROJECT\\recursos/logo.JPG"))
        self.logotipo.setScaledContents(True)
        self.logotipo.setObjectName("logotipo")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ScPrime Monitor"))
        self.buttonConnect.setText(_translate("mainWindow", "Conectar"))
        self.label.setText(_translate("mainWindow", "HOST"))
        self.label_2.setText(_translate("mainWindow", "PASS"))
        self.label_3.setText(_translate("mainWindow", "USER"))
